### ISSUE TITLE
monitoring direct memory allocations / usage

### ISSUE THREAD

**Issue by dmk23** [OpenHFT/Chronicle-Map#31] opened 2015-07-10 00:45 UTC
At the moment we are evaluating/comparing the performance/efficiency of storage of different Map implementations in resource constrained environments. Our application generates the records stored into two Maps of ~700K and ~400K each. The keys are short strings, the values are small Java objects with custom (optimal) serializers, manually processing each field.

We are comparing 4 different Map implementations (all latest versions for Java 7):
1. Koloboke HashObjObjMap (updatable)
2. Chronicle Map `ChronicleMapBuilder.of(String.class, Record.class).create()`
3. MapDB BTreeMap (with packed B-trees)
4. MapDB HTreeMap (more like a regular hash map)

To analyze memory consumption we've instrumented our test with calls to `Runtime.getRuntime().[free|total|max]Memory()` for heap and `sun.misc.SharedSecrets.getJavaNioAccess(). getDirectBufferPool().get[Count|MemoryUsed|TotalCapacity]]()` for direct. Additionally we've recorded the Java process's RSS size at the end of each tests.

First, Chronicle Map did the best, beating out even Koloboke in both time to completion (by ~5%) and in the process RSS size (by ~15%). MapDB maps fell somewhere in the middle by RSS size with BTreeMap being much slower (by ~40%, owing to BTree restructurings) and HTreeMap being just slightly slower (~5%) than Koloboke. The heap usage (after forced full GC) looked as expected in all cases.

What seemed unusual is that `sun.misc` methods for estimating direct memory produced rather strange results. The numbers were essentially the same (negligible) for Koloboke and Chronicle, while for MapDB grew to represent what reasonably seems like the actual size of the data (~60M for BTree, ~90M for HTree to ~200M for Koloboke on the fully shrunk heap with the map and not much else).

After seeing these results I wonder what would be the proper way to estimate actual consumption of direct memory by the Chronicle Map. RSS might not be a good metric as it could get over-inflated by garbage (at least in the case of our producer application - we had ~1.5G, ~1.3G and ~1.4G for Koloboke, Chronicle and MapDBs). I did find that Chronicle uses `unsafe.allocateMemory` vs. `ByteBuffer.allocateDirect`, but in any case I'd like to figure out how to sanity-check our memory usage.

Additionally, for mmap'd files is there a way to tell JVM/Linux how much of those should be loaded into RAM? In case of multiple files is it possible to prioritize caching of one file over another?

**Comment by peter-lawrey** [comment] 2015-07-10 06:57
Hello dm23,
   The approach we use to see how much of an mmap file is utilised is to
look at the du command on the file created.  This is how much of the file
has been populated and is an upper bound on how much is actually in
memory.  If you don't want to be slowed down by a disk sub-system, you can
place the file on a tmpfs filesystem.

  The OS prioritises on a page by page basis, based on a clock based LRU
strategy.  If a page is hot it will stay in memory, if there is memory
pressure and some pages need to be discarded, it is the pages which haven't
been used in a while which are discarded.

   If you want to see how much virtual memory has been allocated you can
look at /proc/{pid}/mmap however Chronicle Map allocates virtual memory
quite freely on the assumption that virtual memory is cheap.

  To see a real difference in terms of performance you could try allocating
map sizes close to main memory and see how the performance drops off at say
80%, 90% 100% 110% 120% of main memory.

Regards,
   Peter.

**Comment by dmk23** [comment] 2015-07-10 12:46
Looking at the attributes of the file makes perfect sense, but I do not see how this would work for direct memory allocations not persisted to a file. Just for a quick test I re-ran my examples (non-persisted) and confirmed that there was nothing created in /proc/{pid}/mmap

Are there any ways to measure direct memory allocated by JVM that's not backed by a file? Or the only way to run some estimates is to always create file-backed maps? Don't they always run the risk of being slower than direct memory should the OS decide to swap them out if short on resources? I am curious if most Chronicle Map users always deploy it in a mmap scenario or use as a pure in-memory cache too?

Is there any way to control mmap page flushing / caching behavior beside choosing to put it onto tmpfs? Any parameters that could affect the LRU algorithm and the IO load? Is there a way to warm up / pre-load a newly opened pre-existing file?

It also seems to me that compactness / layout of the file (i.e. number of map entries per page) could contribute a lot to availability in under-resourced scenario. What could be done from the standpoint of map configuration to affect this? I suppose the parameters on entry sizing, chunks and segments may have a big impact? Would be great to better understand their behavior.

For example if the entry size is too big, would this cause big gaps in the file or if it is too small would trying to serialize just a single extra byte cause errors? It was not very clear from the docs whether entry sizing is a hard limit or a soft hint - trying to understand how it is applied....

**Comment by peter-lawrey** [comment] 2015-07-10 13:35
Hello dm23,
   On Linux and other operating systems, an allocation of 128 KB of
directory memory or more results in an anonymous mmap.  Only smaller
allocations are taken from a pool.
   If the file is stored on a tmpfs file system, there is no more
performance over head than using private native memory.
   If your system is low on resources a file will be pages or a program
will be swapped to swap space.  The problem is the same, the difference is
where the data has to be written to disk.  Note: paged files are written
out more aggressively by default which is usually good for other memory
uses as these will be kept in memory in preference.
   You can tune the dirty page flushing settings in the /etc/sysctl.conf
e.g.

vm.dirty_background_ratio = 20
vm.dirty_ratio = 40

>  Is there a way to warm up / pre-load a newly opened pre-existing file?
yes, read the file sequentially.

> What could be done from the standpoint of map configuration to affect
this?
Don't over allocate your data structure too much.  The main leavers are
entry count and average entry size.  However, Chronicle Map tries to limit
consumption to what you actually use so these are only a guide.  It is
usually a good idea to give yourself some head room.

The biggest thing to remember is to make your you have the
right hardware for the job.  You can spend days tuning a database but it is
usually far, far cheaper to buy a little more memory.  Every hour you spend
is worth 1.5 GB assuming you are on minimum wage (in the UK) Put another
way, if you spend a day tuning a system and don't save 12 GB memory usage
it probably wasn't a good use of your time.  Note: while your hardware
might be more expensive than retail, you are probably costing your company
more than minimum wage.

> the entry size is too big, would this cause big gaps in the file

Not if it's a little too big.  If you make ti twice what it should be, this
isn't much of a problem.  You make it 100x what it should be, AND you have
really small entries i.e. << 4 KB, this could mean you sue 4 KB per entry.
If you set the average size to 1 MB but use 8 KB per entry, this will only
waste virtual memory on Linux.

The entries * entry size is a hard limit which is why it is usually better
to over size the number of entries, as the difference to performance is
relatively small.

Regards,
   peter.

**Comment by peter-lawrey** [comment] 2015-07-10 13:37
Hello dm23,
   Can you email me so we can discuss your specific use case? on
peter.lawrey@chroncile.software

Regards,
   Peter.

**Comment by minborg** [comment] 2022-01-03 15:54
Closing as there is nothing more to do.

**Closed by minborg** 2022-01-03 15:54 UTC
Labels: enhancement
