### ISSUE TITLE
Getting tools.jar issue with Chronicle-Map Release version

### ISSUE THREAD

**Issue by nitina82** [OpenHFT/Chronicle-Map#215] opened 2020-04-24 01:13 UTC
Hello Team,

I am trying to use Chronicle Map in my java project. To be clear i am referring latest version 3.19.4.

Getting below error.
 There was a problem while copying the artifact [com.sun:tools:1.8.0_241:jar] file [/C:/Program Files/Java/jdk1.8.0_241/lib/tools.jar] to the application local repository

Caused by: java.io.FileNotFoundException: Source 'C:\Program Files\Java\jdk1.8.0_241\jre\..\lib\pom.xml' does not exist

Found some old reference where it was suggested to exclude tools jar like below. Still doesn't work.
```
<dependency>
            <groupId>net.openhft</groupId>
            <artifactId>chronicle-map</artifactId>
            <version>3.19.4</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sun.java</groupId>
                    <artifactId>tools</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

Secondly, If i lower down the version to 3.17.0, I get below error..
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact net.openhft:third-party-bom:pom:3.6.5 from/to central (http://repo.maven.apache.org/maven2): HTTPS Required (501)

Seems the pom.xml has http instead to https. 

```
<repository>
            <id>central</id>
            <name>Central Repository</name>
            <url>http://repo.maven.apache.org/maven2</url>
            <layout>default</layout>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
```
Any suggestions?

**Comment by dpisklov** [comment] 2020-04-24 17:19
Duplicate of #1
There's the whole thread there on how to debug this issue. Once you followed all suggestions and if you still have an issue please describe it there in details (hint: statement "still doesn't work" doesn't have enough details).
As for the second problem - it is not ours, see https://blog.sonatype.com/central-repository-moving-to-https - we updated our links subsequently.

**Closed by dpisklov** 2020-04-24 17:19 UTC
