### ISSUE TITLE
how to solve the  "error: symbol not found" for LongValue$$Heap.java and LongValue$$Native.java?

### ISSUE THREAD

**Issue by smiley886** [OpenHFT/Chronicle-Map#473] opened 2023-02-25 16:15 UTC
I am using Chronicle-Map version 3.23.5, and I also set --illegal-access=permit in my modular project in JDK17, when I create a ChronicleMap<LongValue, ByteBuffer>, it reported "...net.openhft.chronicle.core...error: symbol not found", what should I do?

**Comment by smiley886** [comment] 2023-02-26 00:31
It reports the "Error: Symbol not found" of LongValue, Can anyone help me?

**Comment by smiley886** [comment] 2023-02-26 02:36
LongValue$$Heap.java and LongValue$$Native.java report "error: symbol not found" respectively.

**Comment by smiley886** [comment] 2023-02-26 12:32
I found that the error only occurs in modular projects, which makes me depressed....

**Comment by smiley886** [comment] 2023-02-27 01:58
I found that this error may be related to the environment variable "java.class.path", after I use System.setProperty method to force the paths of the Chronicle‘s libraries to this environment variable, the program no longer reports this error, but there is a new However, there is a new problem, that is, the program becomes very laggy, and any operation on the program interface will cause the cpu usage to increase dramatically, even if these operations have nothing to do with the Chronicle object.

**Comment by alamar** [comment] 2023-02-28 11:32
Seems to be a duplicate of OpenHFT/Chronicle-Core#485 - closing

**Closed as completed by alamar** 2023-02-28 11:32 UTC
