### ISSUE TITLE
"Wrong lowest free chunk" after graceful restart

### ISSUE THREAD

**Issue by lyutenko** [OpenHFT/Chronicle-Map#124] opened 2017-05-24 15:31 UTC
Hi we use version: 3.13.0
we keep 10.000 entries persisted to disk and modify them, so create map in this way: 
` ChronicleMap<UUID, Long> requestIdSet = ChronicleMap.of(UUID.class, Long.class).averageKey(UUID.randomUUID()).entries(maxEntries).createOrRecoverPersistedTo(historyFile, false);`

and close the map whenever we shutdown application:

`public void onApplicationClose() {
            requestIdSet.close();
            LOGGER.info("Closing ChronicleMap backed PutRequestHistory");
     }`

But after application restart, we see this in log:

[Thread-8] 05-24 14:23:40.544  INFO ChronicleMapPutRequestStorage - Closing ChronicleMap backed PutRequestHistory

[main] 05-24 14:23:59.514 ERROR ChronicleMap - wrong lowest free chunk for tier with index 4, stored: 8370, should be: 15492

 [main] 05-24 14:23:59.570 ERROR ChronicleMap - wrong lowest free chunk for tier with index 12, stored: 8436, should be: 12552

 [main] 05-24 14:23:59.593 ERROR ChronicleMap - wrong lowest free chunk for tier with index 22, stored: 8232, should be: 12552

 [main] 05-24 14:23:59.601 ERROR ChronicleMap - wrong lowest free chunk for tier with index 25, stored: 8394, should be: 14238

 [main] 05-24 14:23:59.609 ERROR ChronicleMap - wrong lowest free chunk for tier with index 28, stored: 8250, should be: 16362

 [main] 05-24 14:23:59.615 ERROR ChronicleMap - wrong lowest free chunk for tier with index 30, stored: 8364, should be: 15030

 [main] 05-24 14:23:59.621 ERROR ChronicleMap - wrong lowest free chunk for tier with index 32, stored: 8292, should be: 14196

 [main] 05-24 14:23:59.662  INFO ChronicleMapPutRequestStorage - ChronicleMapPutRequestStorage loaded 100000 entries

So we close map gracefully we see this in log and after this when new process started, after previous fully exited we see these error messages.
Also we have in log how much entries is loaded (last log entry - so its correct it loaded 10.000 entries which we keep and update always)

`LOGGER.info("ChronicleMapPutRequestStorage loaded {} entries", requestIdSet.size());`

There are no more exceptions later during we work with this map, but what actually happens? could entries be corrupted or smth like this (we use this map only by single JVM all the time)?

Thanks.

**Comment by leventov** [comment] 2017-06-05 03:40
Could you please prepare a reproducible example?

**Comment by sebastian-schmitt** [comment] 2018-09-21 13:08
Dear Roman,
we encounter the same issue as stated above. The problem is, that I was not able to setup a small reproducible example. Here is our current situation:

1. we have a our map filled with about 1.2 million entries, mapping string-keys to json-values.
2. To (un)marshall our values, we implemented a custom marshaller - which is implemented for now using a naïve `bytes.writeUtf8(toWrite.toString())`.
3. initially, we started using a worker-threadpool of four workers that operate on the chronicle map. Now I have this pool size down to one single thread - which still leads to segment-corruption.
4. We close our map inside a JVM-Shutdown-Hook. 

Our (kotlin-) code that creates the map looks like this:

```
ChronicleMap.of(String::class.java, JsonMap::class.java)
            .averageKeySize(Tools.randomId().length.toDouble())
            .valueMarshaller(JsonMarshaller)
            .name("chronicle.Persistables")
            .entries(20_000_000) 
            .averageValueSize(256.0) //TODO re-estimate this!
            .let {
                if (recover) it.recoverPersistedTo(dataFile, true)
                else it.createPersistedTo(dataFile)
            }.also { Log.info("loaded database with ${it.size} entries.") }
```


the corresponding Json-Marshaller looks like this:

```
object JsonMarshaller : BytesWriter<JsonMap>, BytesReader<JsonMap>, ReadResolvable<JsonMarshaller> {
    override fun write(bytes: Bytes<*>, toWrite: JsonMap) = Unit.also { bytes.writeUtf8(toWrite.toString()) }
    override fun read(bytes: Bytes<*>, using: JsonMap?) = JsonFactory.parseMap(bytes.readUtf8()!!)
    override fun readResolve() = this
}
```

I guess, our project is too work-intensive to setup for you - so maybe I could produce some logs of these runs that lead to segment-corruption. We have configured log4j2, but I could not manage to see any chronicle-related logs there. Could you give me a hint here? This is what our configuration file looks like:

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="warn" name="tumult">
    <Appenders>
        <RollingFile name="RollingFile" fileName="logs/trump.log"
                     filePattern="logs/$${date:yyyy-MM}/trump-%d{MM-dd-yyyy}-%i.log.gz">
            <PatternLayout>
                <Pattern>%d %p %c{1.} [%t] %m%n</Pattern>
            </PatternLayout>
            <Policies>
                <TimeBasedTriggeringPolicy/>
                <SizeBasedTriggeringPolicy size="250 MB"/>
            </Policies>
        </RollingFile>

        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
        </Console>

    </Appenders>


    <Loggers>
        <Logger name="net.openhft.chronicle" level="TRACE">
            <AppenderRef ref="Console"/>
            <AppenderRef ref="RollingFile"/>
        </Logger>

        <Root level="info">
            <AppenderRef ref="Console"/>
            <AppenderRef ref="RollingFile"/>
        </Root>
    </Loggers>
</Configuration>
```

**Comment by mrbald** [comment] 2020-03-31 07:13
Having the same errors with version 3.19.3. Gracefully closing the store on shutdown, definitely not writing anything while closing.
On restart - dozens of "wrong lowest free chunk for tier with index ..." errors.
Debian 9 / OpenJDK 8.

**Comment by dpisklov** [comment] 2020-04-01 18:27
@mrbald can you provide a reproducible test case?

**Comment by minborg** [comment] 2022-01-03 15:06
We have updated Chronicle Map in recent versions. Please indicate if the problem persists in `2.22ea21` @mrbald @sebastian-schmitt and @lyutenko and if so, please provide a reproducible test we can run.

**Comment by minborg** [comment] 2022-01-05 14:28
Absent any comments, I am closing this issue for now. Please reopen if the error persist in 2.22ea21 or later.

**Closed by minborg** 2022-01-05 14:28 UTC
