### ISSUE TITLE
Exception thrown when iterating over keys with UTF-8 encoded key

### ISSUE THREAD

**Issue by NickWard** [OpenHFT/Chronicle-Map#148] opened 2018-04-09 10:49 UTC
Possibly bad data in the key:
```
Caused by: net.openhft.chronicle.bytes.UTFDataFormatRuntimeException: malformed input around byte 5
at net.openhft.chronicle.bytes.BytesInternal.parseUtf82(BytesInternal.java:529)
at net.openhft.chronicle.bytes.BytesInternal.parseUtf8_SB1(BytesInternal.java:406)
at net.openhft.chronicle.bytes.BytesInternal.parseUtf8(BytesInternal.java:134)
at net.openhft.chronicle.bytes.StreamingDataInput.readUtf8(StreamingDataInput.java:212)
at net.openhft.chronicle.bytes.BytesInternal.readUtf8(BytesInternal.java:1596)
at net.openhft.chronicle.bytes.StreamingDataInput.readUtf8(StreamingDataInput.java:181)
at net.openhft.chronicle.bytes.BytesMarshaller$ScalarFieldAccess.setValue(BytesMarshaller.java:184)
at net.openhft.chronicle.bytes.BytesMarshaller$FieldAccess.read(BytesMarshaller.java:148)
at net.openhft.chronicle.bytes.BytesMarshaller.readMarshallable(BytesMarshaller.java:63)
at net.openhft.chronicle.bytes.BytesUtil.readMarshallable(BytesUtil.java:170)
at net.openhft.chronicle.bytes.BytesMarshallable.readMarshallable(BytesMarshallable.java:27)
at net.openhft.chronicle.hash.serialization.impl.BytesMarshallableReader.read(BytesMarshallableReader.java:45)
at net.openhft.chronicle.hash.serialization.impl.BytesMarshallableReader.read(BytesMarshallableReader.java:27)
at net.openhft.chronicle.hash.serialization.impl.BytesAsSizedReader.read(BytesAsSizedReader.java:42)
at net.openhft.chronicle.map.impl.CompiledMapIterationContext$EntryKeyBytesData.innerGetUsing(CompiledMapIterationContext.java:456)
at net.openhft.chronicle.map.impl.CompiledMapIterationContext$EntryKeyBytesData.getUsing(CompiledMapIterationContext.java:496)
at net.openhft.chronicle.map.ChronicleMapIterator$OfKeys.read(ChronicleMapIterator.java:129)
at net.openhft.chronicle.map.ChronicleMapIterator.accept(ChronicleMapIterator.java:69)
at net.openhft.chronicle.map.ChronicleMapIterator$OfKeys.accept(ChronicleMapIterator.java:121)
at net.openhft.chronicle.map.impl.CompiledMapIterationContext.lambda$forEachSegmentEntry$22(CompiledMapIterationContext.java:3949)
at net.openhft.chronicle.map.impl.CompiledMapIterationContext.forEachTierEntryWhile(CompiledMapIterationContext.java:3888)
at net.openhft.chronicle.map.impl.CompiledMapIterationContext.innerForEachSegmentEntryWhile(CompiledMapIterationContext.java:3923)
at net.openhft.chronicle.map.impl.CompiledMapIterationContext.forEachSegmentEntryWhile(CompiledMapIterationContext.java:3943)
at net.openhft.chronicle.map.impl.CompiledMapIterationContext.forEachSegmentEntry(CompiledMapIterationContext.java:3948)
at net.openhft.chronicle.map.ChronicleMapIterator.fillEntryBuffer(ChronicleMapIterator.java:61)
at net.openhft.chronicle.map.ChronicleMapIterator.hasNext(ChronicleMapIterator.java:77)
at com.googlecode.cqengine.persistence.support.CollectionWrappingObjectStore$1.hasNext(CollectionWrappingObjectStore.java:62)
at com.googlecode.cqengine.persistence.support.ObjectSet$ObjectStoreAsObjectSet$1.hasNext(ObjectSet.java:132)
at com.googlecode.cqengine.index.support.AbstractMapBasedAttributeIndex.addAll(AbstractMapBasedAttributeIndex.java:73)
at com.googlecode.cqengine.index.support.AbstractMapBasedAttributeIndex.init(AbstractMapBasedAttributeIndex.java:139)
at com.googlecode.cqengine.engine.CollectionQueryEngine.addAttributeIndex(CollectionQueryEngine.java:198)
at com.googlecode.cqengine.engine.CollectionQueryEngine.addIndex(CollectionQueryEngine.java:160)
at com.googlecode.cqengine.ConcurrentIndexedCollection.addIndex(ConcurrentIndexedCollection.java:173)
```
>

**Comment by minborg** [comment] 2022-01-04 14:19
I am closing this issue now in anticipation that the problem is fixed. If not, please provide a reproducing test and reopen the issue.

**Closed by minborg** 2022-01-04 14:19 UTC
